# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
- name: Install nodepool using pip
  become: true
  pip:
    executable: "{{ nodepool_pip_executable|default(omit) }}"
    editable: "{{ nodepool_pip_editable|default(omit) }}"
    extra_args: "{{ nodepool_pip_extra_args|default(omit) }}"
    name: "{{ nodepool_pip_name }}"
    version: "{{ nodepool_pip_version|default(omit) }}"
    virtualenv_python: "{{ nodepool_pip_virtualenv_python|default(omit) }}"
    virtualenv: "{{ nodepool_pip_virtualenv|default(omit) }}"

- name: Symlink nodepool virtualenv
  become: true
  file:
    src: "{{ nodepool_pip_virtualenv }}"
    dest: "{{ nodepool_pip_virtualenv_symlink }}"
    state: link
  when:
    - nodepool_pip_virtualenv is defined
    - nodepool_pip_virtualenv_symlink is defined
    - nodepool_pip_virtualenv != nodepool_pip_virtualenv_symlink
