# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
- name: Define nodepool_file_nodepool_service_dest.
  set_fact:
    nodepool_file_nodepool_service_dest: "{{ __nodepool_file_nodepool_service_dest }}"
  when: nodepool_file_nodepool_service_dest is not defined

- name: Define nodepool_file_nodepool_service_mode.
  set_fact:
    nodepool_file_nodepool_service_mode: "{{ __nodepool_file_nodepool_service_mode }}"
  when: nodepool_file_nodepool_service_mode is not defined

- name: Define nodepool_file_nodepool_service_src.
  set_fact:
    nodepool_file_nodepool_service_src: "{{ __nodepool_file_nodepool_service_src }}"
  when: nodepool_file_nodepool_service_src is not defined

- name: Define nodepool_file_nodepool_service_config_dest.
  set_fact:
    nodepool_file_nodepool_service_config_dest: "{{ __nodepool_file_nodepool_service_config_dest  }}"
  when: nodepool_file_nodepool_service_config_dest is not defined

- name: Define nodepool_file_nodepool_service_config_mode.
  set_fact:
    nodepool_file_nodepool_service_config_mode: "{{ __nodepool_file_nodepool_service_config_mode  }}"
  when: nodepool_file_nodepool_service_config_mode is not defined

- name: Define nodepool_file_nodepool_service_config_src.
  set_fact:
    nodepool_file_nodepool_service_config_src: "{{ __nodepool_file_nodepool_service_config_src  }}"
  when: nodepool_file_nodepool_service_config_src is not defined

- name: Define nodepool_file_nodepool_builder_service_dest.
  set_fact:
    nodepool_file_nodepool_builder_service_dest: "{{ __nodepool_file_nodepool_builder_service_dest }}"
  when: nodepool_file_nodepool_builder_service_dest is not defined

- name: Define nodepool_file_nodepool_builder_service_mode.
  set_fact:
    nodepool_file_nodepool_builder_service_mode: "{{ __nodepool_file_nodepool_builder_service_mode }}"
  when: nodepool_file_nodepool_builder_service_mode is not defined

- name: Define nodepool_file_nodepool_builder_service_src.
  set_fact:
    nodepool_file_nodepool_builder_service_src: "{{ __nodepool_file_nodepool_builder_service_src }}"
  when: nodepool_file_nodepool_builder_service_src is not defined

- name: Define nodepool_file_nodepool_builder_service_config_dest.
  set_fact:
    nodepool_file_nodepool_builder_service_config_dest: "{{ __nodepool_file_nodepool_builder_service_config_dest  }}"
  when: nodepool_file_nodepool_builder_service_config_dest is not defined

- name: Define nodepool_file_nodepool_builder_service_config_mode.
  set_fact:
    nodepool_file_nodepool_builder_service_config_mode: "{{ __nodepool_file_nodepool_builder_service_config_mode  }}"
  when: nodepool_file_nodepool_builder_service_config_mode is not defined

- name: Define nodepool_file_nodepool_builder_service_config_src.
  set_fact:
    nodepool_file_nodepool_builder_service_config_src: "{{ __nodepool_file_nodepool_builder_service_config_src  }}"
  when: nodepool_file_nodepool_builder_service_config_src is not defined

- name: Copy nodepool services scripts into place.
  become: yes
  copy:
    dest: "{{ nodepool_file_nodepool_service_dest }}"
    group: "{{ nodepool_file_nodepool_service_group }}"
    mode: "{{ nodepool_file_nodepool_service_mode }}"
    owner: "{{ nodepool_file_nodepool_service_owner }}"
    src: "{{ nodepool_file_nodepool_service_src }}"
  register: nodepool_file_nodepool_service

- name: Copy nodepool service config into place.
  become: yes
  copy:
    dest: "{{ nodepool_file_nodepool_service_config_dest  }}"
    group: "{{ nodepool_file_nodepool_service_config_group  }}"
    mode: "{{ nodepool_file_nodepool_service_config_mode  }}"
    owner: "{{ nodepool_file_nodepool_service_config_owner  }}"
    src: "{{ nodepool_file_nodepool_service_config_src  }}"
  register: nodepool_file_nodepool_service_config

- name: Copy nodepool-builder services scripts into place.
  become: yes
  copy:
    dest: "{{ nodepool_file_nodepool_builder_service_dest }}"
    group: "{{ nodepool_file_nodepool_builder_service_group }}"
    mode: "{{ nodepool_file_nodepool_builder_service_mode }}"
    owner: "{{ nodepool_file_nodepool_builder_service_owner }}"
    src: "{{ nodepool_file_nodepool_builder_service_src }}"
  register: nodepool_file_nodepool_builder_service

- name: Copy nodepool service config into place.
  become: yes
  copy:
    dest: "{{ nodepool_file_nodepool_builder_service_config_dest  }}"
    group: "{{ nodepool_file_nodepool_builder_service_config_group  }}"
    mode: "{{ nodepool_file_nodepool_builder_service_config_mode  }}"
    owner: "{{ nodepool_file_nodepool_builder_service_config_owner  }}"
    src: "{{ nodepool_file_nodepool_builder_service_config_src  }}"
  register: nodepool_file_nodepool_builder_service_config

- name: Enable nodepool service.
  become: yes
  service:
    enabled: "{{ nodepool_service_nodepool_enabled }}"
    name: "{{ nodepool_service_nodepool_name }}"
    state: "{{ nodepool_service_nodepool_state }}"
  register: nodepool_service_nodepool
  when: nodepool_service_nodepool_manage

- name: Enable nodepool-builder service.
  become: yes
  service:
    enabled: "{{ nodepool_service_nodepool_builder_enabled }}"
    name: "{{ nodepool_service_nodepool_builder_name }}"
    state: "{{ nodepool_service_nodepool_builder_state }}"
  register: nodepool_service_nodepool_builder
  when: nodepool_service_nodepool_builder_manage
